export const navigation_list = [
  {
    name: "Home",
    link: "/",
  },
  {
    name: "Blog",
    link: "/blog",
  },
  {
    name: "Events",
    link: "/events",
  },
  {
    name: "AACA",
    link: "/aaca",
  },
  {
    name: "Contact",
    link: "/contact",
  },
];

export const affiliates_list = [
  {
    name: "Barpeta District Chess Association",
    phone: 7086255583,
    email: "durlavk98@gmail.com",
    type: "district",
    secretary: "Durlav Kalita",
  },
  {
    name: "Cachar District Chess Association",
    phone: 7086255583,
    email: "durlavk98@gmail.com",
    type: "district",
    secretary: "Durlav Kalita",
  },
  {
    name: "Dibrugarh District Chess Association",
    phone: 7086255583,
    email: "durlavk98@gmail.com",
    type: "district",
    secretary: "Durlav Kalita",
  },
  {
    name: "Duliajan Chess Academy, Duliajan Club",
    phone: 7086255583,
    email: "durlavk98@gmail.com",
    type: "district",
    secretary: "Durlav Kalita",
  },
  {
    name: "Gauhati Town Club Chess Foundation",
    phone: 7086255583,
    email: "durlavk98@gmail.com",
    type: "district",
    secretary: "Durlav Kalita",
  },
  {
    name: "Golaghat District Chess Association",
    phone: 7086255583,
    email: "durlavk98@gmail.com",
    type: "district",
    secretary: "Durlav Kalita",
  },
  {
    name: "Guwahati Chess Association",
    phone: 7086255583,
    email: "durlavk98@gmail.com",
    type: "district",
    secretary: "Durlav Kalita",
  },
  {
    name: "Hailakandi District Chess Association",
    phone: 7086255583,
    email: "durlavk98@gmail.com",
    type: "district",
    secretary: "Durlav Kalita",
  },
  {
    name: "Hojai District Chess Association",
    phone: 7086255583,
    email: "durlavk98@gmail.com",
    type: "district",
    secretary: "Durlav Kalita",
  },
  {
    name: "Jorhat District Chess Association",
    phone: 7086255583,
    email: "durlavk98@gmail.com",
    type: "district",
    secretary: "Durlav Kalita",
  },
  {
    name: "Kaliabor District Chess Association",
    phone: 7086255583,
    email: "durlavk98@gmail.com",
    type: "district",
    secretary: "Durlav Kalita",
  },
  {
    name: "Kamrup District (Rural) Chess Association",
    phone: 7086255583,
    email: "durlavk98@gmail.com",
    type: "district",
    secretary: "Durlav Kalita",
  },
  {
    name: "Karimganj District. Chess Association",
    phone: 7086255583,
    email: "durlavk98@gmail.com",
    type: "district",
    secretary: "Durlav Kalita",
  },
  {
    name: "Kokrajhar District Chess Association",
    phone: 7086255583,
    email: "durlavk98@gmail.com",
    type: "district",
    secretary: "Durlav Kalita",
  },
  {
    name: "Mangaldoi District Chess Association",
    phone: 7086255583,
    email: "durlavk98@gmail.com",
    type: "district",
    secretary: "Durlav Kalita",
  },
  {
    name: "Morigaon District Chess Association",
    phone: 7086255583,
    email: "durlavk98@gmail.com",
    type: "district",
    secretary: "Durlav Kalita",
  },
  {
    name: "Nagaon District Chess association",
    phone: 7086255583,
    email: "durlavk98@gmail.com",
    type: "district",
    secretary: "Durlav Kalita",
  },
  {
    name: "North Lakhimpur District Chess Association",
    phone: 7086255583,
    email: "durlavk98@gmail.com",
    type: "district",
    secretary: "Durlav Kalita",
  },
  {
    name: "Oil India Ltd., Duliajan",
    phone: 7086255583,
    email: "durlavk98@gmail.com",
    type: "district",
    secretary: "Durlav Kalita",
  },
  {
    name: "P. C. Borooah Chess Academy",
    phone: 7086255583,
    email: "durlavk98@gmail.com",
    type: "district",
    secretary: "Durlav Kalita",
  },
  {
    name: "Sivasagar District Chess Association",
    phone: 7086255583,
    email: "durlavk98@gmail.com",
    type: "district",
    secretary: "Durlav Kalita",
  },
  {
    name: "Tezpur District Chess Association",
    phone: 7086255583,
    email: "durlavk98@gmail.com",
    type: "district",
    secretary: "Durlav Kalita",
  },
  {
    name: "Tinsukia District Chess Association",
    phone: 7086255583,
    email: "durlavk98@gmail.com",
    type: "district",
    secretary: "Durlav Kalita",
  },
];
